storePassword=Sourabh
keyPassword=Sourabh
keyAlias=my-key-alias
storeFile=C:\\Users\\nuzha\\Desktop\\Sourabh\\5k\\Restaurent_Management\\frontend\\restaurent_app\\android\\5k-upload-keystore.jks
# storeFile=C:\\Users\\soura\\Desktop\\5K\\Restaurent_Management\\frontend\\restaurent_app\\android\\5k-upload-keystore.jks