// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV2CEpy47iN1Sz5AkjqazWn8-THXAFNn0',
    appId: '1:867406387464:web:49f7e3b492c2bea2fb34bd',
    messagingSenderId: '867406387464',
    projectId: 'k-restaurant-eef0f',
    authDomain: 'k-restaurant-eef0f.firebaseapp.com',
    storageBucket: 'k-restaurant-eef0f.firebasestorage.app',
    measurementId: 'G-LS04C02V78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD26pontUWvvNg_V_9AI3tZQCUf_yltnAI',
    appId: '1:867406387464:android:fdcb191801fd3e8bfb34bd',
    messagingSenderId: '867406387464',
    projectId: 'k-restaurant-eef0f',
    storageBucket: 'k-restaurant-eef0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoVf4iSp1fp3kY94vqfWtP_XZWn-EWDBo',
    appId: '1:867406387464:ios:d59573efadb179c7fb34bd',
    messagingSenderId: '867406387464',
    projectId: 'k-restaurant-eef0f',
    storageBucket: 'k-restaurant-eef0f.firebasestorage.app',
    iosBundleId: 'com.tobasu.Neevika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoVf4iSp1fp3kY94vqfWtP_XZWn-EWDBo',
    appId: '1:867406387464:ios:d59573efadb179c7fb34bd',
    messagingSenderId: '867406387464',
    projectId: 'k-restaurant-eef0f',
    storageBucket: 'k-restaurant-eef0f.firebasestorage.app',
    iosBundleId: 'com.tobasu.Neevika',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV2CEpy47iN1Sz5AkjqazWn8-THXAFNn0',
    appId: '1:867406387464:web:d41d6f1e4a62a62bfb34bd',
    messagingSenderId: '867406387464',
    projectId: 'k-restaurant-eef0f',
    authDomain: 'k-restaurant-eef0f.firebaseapp.com',
    storageBucket: 'k-restaurant-eef0f.firebasestorage.app',
    measurementId: 'G-BWB8MDFB53',
  );
}
